# Environment / application
url=https://opensource-demo.orangehrmlive.com/
browser=chrome
timeout=10
headless=false       # <-- add this for GitHub Actions CI

# Valid login
username=Admin
password=admin123

# Invalid login (for negative test)
invalidUsername=admin
invalidPassword=wrong