# Environment / application
url=https://opensource-demo.orangehrmlive.com/
browser=chrome
timeout=10

# Valid login
username=Admin
password=admin123

# Invalid login (for negative test)
invalidUsername=admin
invalidPassword=wrong



#Login Credentials
username=Admin
Password=admin123
